# Generated by Django 3.1.1 on 2020-09-24 19:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='invoice_receipts/')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9999)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.invoice')),
            ],
        ),
    ]
