# Generated by Django 3.1.1 on 2020-09-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='receipt_image',
            new_name='reciept_image',
        ),
    ]
