# Generated by Django 3.1.1 on 2020-09-26 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20200925_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
